http:
  port: 8080

admin:
  port: 9877
  host: localhost

apiEndpoints:
  products:
    path: /products/*
    methods: [OPTIONS, GET, POST, PUT, DELETE]
  customers:
    path: /customers/*
    methods: [OPTIONS, GET, POST, PUT, DELETE]
  suppliers:
    path: /suppliers/*
    methods: [OPTIONS, GET, POST, PUT, DELETE]
  sales:
    path: /sales/*
    methods: [OPTIONS, GET, POST, PUT, DELETE]
  invoices:
    path: /invoices/*
    methods: [OPTIONS, GET, POST, PUT, DELETE]
  returns:
    path: /returns/*
    methods: [OPTIONS, GET, POST, PUT, DELETE]
  expenses:
    path: /expenses/*
    methods: [OPTIONS, GET, POST, PUT, DELETE]
  reports:
    path: /reports/*
    methods: [OPTIONS, GET, POST]
  auth:
    path: /auth/*
    methods: [OPTIONS, GET, POST]

serviceEndpoints:
  auth-service:
    url: http://localhost:3012
  products-service:
    url: http://localhost:3001
  customers-service:
    url: http://localhost:3002
  sales-service:
    url: http://localhost:3003
  invoices-service:
    url: http://localhost:3004
  returns-service:
    url: http://localhost:3005
  expenses-service:
    url: http://localhost:3006
  reports-service:
    url: http://localhost:3007
  suppliers-service:
    url: http://localhost:3008

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  auth-pipeline:
    apiEndpoints:
      - auth
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: auth-service
            stripPath: false

  products-pipeline:
    apiEndpoints:
      - products
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: products-service
            stripPath: true

  customers-pipeline:
    apiEndpoints:
      - customers
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: customers-service
            stripPath: true

  suppliers-pipeline:
    apiEndpoints:
      - suppliers
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: suppliers-service
            stripPath: true

  sales-pipeline:
    apiEndpoints:
      - sales
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: sales-service
            stripPath: true

  invoices-pipeline:
    apiEndpoints:
      - invoices
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: invoices-service
            stripPath: true

  returns-pipeline:
    apiEndpoints:
      - returns
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: returns-service
            stripPath: true

  expenses-pipeline:
    apiEndpoints:
      - expenses
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST,PUT,DELETE,OPTIONS'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: expenses-service
            stripPath: true

  reports-pipeline:
    apiEndpoints:
      - reports
    policies:
      - cors:
          action:
            origin:
              - 'http://localhost:33117'
              - 'https://pos-app-sooty.vercel.app'
            methods: 'GET,POST'
            allowedHeaders: 'Content-Type, Authorization'
            credentials: true
      - proxy:
          action:
            serviceEndpoint: reports-service
            stripPath: true
